import axios from 'axios';
import Head from 'next/head';
import { useState } from 'react';

export default function Home() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [filePdf, setFilePdf] = useState(null);

  const handleFileChange = (e) => {
    setFilePdf(e.target.files[0]);
  };

  const postTest = (e) => {
    e.preventDefault();

    // Upload the file to Telegram using FormData
    const formData = new FormData();
    formData.append('chat_id', '-1001553163227'); // Replace with your Telegram group ID
    formData.append('document', filePdf);
    formData.append(
      'caption',
      `Name: ${name}\nEmail: ${email}` // Message text with formatting
    );

    axios
      .post(
        `https://api.telegram.org/bot5378253930:AAEW0rlP7j7KA50TxsypNSLLKvQ5jYnNPfc/sendDocument`,
        formData,
        {
          headers: {
            'Content-Type': 'multipart/form-data',
          },
        }
      )
      .then(() => {
        window.location.reload();
      })
      .catch((error) => {
        console.error('Error sending file:', error);
      });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section>
        <form onSubmit={postTest}>
          <input
            value={name}
            onChange={(e) => setName(e.target.value)}
            type='text'
            placeholder='name'
            required
          />
          <input
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            type='email'
            placeholder='email'
            required
          />
          <input type='file' required onChange={handleFileChange} />
          <button type='submit'>Send to Telegram!</button>

        <a className='tg' target='_blank' href="https://t.me/+YJdPUtUHRNo5NTM6">Telegram bot</a>

        </form>
      </section>
    </>
  );
}
